#!/usr/bin/env python3

"""
Tool to remove specific variables from input netCDF file
"""

import xarray as xr
import argparse

def main():
    parser = argparse.ArgumentParser(description='Combine multiple bathymmetry sources into a single grid')
    parser.add_argument('--input', required=True, help='name of input file')
    parser.add_argument('--output', required=True, help='name of output file')
    parser.add_argument('--variable', required=True, help='variable to delete')
    args = parser.parse_args()

    ds = xr.load_dataset(args.input)
    if args.variable in ds:
        del ds[args.variable]
    else:
        raise ValueError(f"Could not find {args.variable} in dataset {args.input}")
    ds.to_netcdf(args.output)

if __name__ == "__main__":
    main()

