name: Pytest

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    name: pyCascadia ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv environment
        run: pipenv install

      - name: Test
        run: pipenv run pytest
