name: Pytest

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: pyCascadia on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python:
          - '3.9'
    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: ${{ matrix.python }}
          conda-channels: conda-forge

      - name: Install conda dependencies
        run: |
          conda install pip
          conda install -c conda-forge pygmt gdal rasterio

      - name: Install package
        run: pip install .[test]

      - name: Test
        run: pytest
