name: Build and publish documentation

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pycascadia
          environment-file: environment.yml
          python-version: 3.9
          auto-activate-base: false

      - name: Install package
        shell: bash -l {0}
        run: pip install .

      - name: Build documentation
        shell: bash -l {0}
        run: |
          conda install pdoc3
          pdoc --html --output-dir build pycascadia

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd build/pycascadia
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./build/pycascadia
